name: Deploy Site
# Heavily inspired by https://github.com/truemedian/discordia-docs/blob/a214cfeca711f0e33d0fa3b0ffc6545d09ee1c73/.github/workflows/release.yml
# and https://github.com/actions/starter-workflows/blob/main/pages/static.yml.

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      # Checkout
      - name: Checkout site repository
        uses: actions/checkout@v3
        with:
          path: site

      - name: Checkout creative writing repository
        uses: actions/checkout@v3
        with:
          repository: RiskoZoSlovenska/creative-writing
          path: creative-writing
          submodules: recursive
          token: ${{ secrets.GIT_CREDENTIALS }}


      # Install dependencies
      - name: Install Lua
        uses: leafo/gh-actions-lua@v10
      
      - name: Install Luarocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Install libyaml # Needed for lyaml
        run: | # https://unix.stackexchange.com/a/85195
          curl -L --retry 5 --retry-delay 30 http://pyyaml.org/download/libyaml/yaml-0.2.5.tar.gz | tar xvz
          cd yaml-0.2.5
          ./configure
          make
          sudo make install

      - name: Install Lua dependencies
        run: |
          luarocks install penlight
          luarocks install dkjson
          luarocks install lyaml
          luarocks install lcmark
          luarocks install cmark
          luarocks install gumbo


      # Build
      - name: Compile stories
        run: lua builds-scripts/compile-stories.lua ../creative-writing
        working-directory: site

      - name: Compile search data
        run: lua build-scripts/compile-search-data.lua
        working-directory: site


      # Deploy
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: site/src

      - name: Deploy Pages artifact
        uses: actions/deploy-pages@v2
