name: Deploy page

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout site repository
        uses: actions/checkout@v3
        with:
          path: site

      - name: Checkout creative writing repository
        uses: actions/checkout@v3
        with:
          repository: RiskoZoSlovenska/creative-writing
          path: creative-writing
          submodules: recursive
          token: ${{ secrets.GIT_CREDENTIALS }}


      - name: Install lua # Must install lua for luarocks to work
        uses: leafo/gh-actions-lua@v8.0.0 
        with:
         luaVersion: "5.1"
      
      - name: Install luarocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Install luvit
        run: curl -L https://github.com/luvit/lit/raw/master/get-lit.sh | sh
        shell: bash

      - name: Install dependencies
        run: |
          luarocks install lunamark
          luarocks install gumbo
          luarocks install lua-yaml

          ./lit install creationix/coro-fs
        shell: bash


      - name: Compile stories
        run: ../luvit compile-stories.lua ../creative-writing
        shell: bash
        working-directory: site

      - name: Compile search data
        run: ../luvit compile-search-data.lua
        shell: bash
        working-directory: site


      - name: Push to deployment branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: site
          branch: gh-pages
          push_options: --force
          skip_checkout: true
          commit_message: Publish site
          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>