name: Deploy Site
# Heavily inspired by https://github.com/truemedian/discordia-docs/blob/a214cfeca711f0e33d0fa3b0ffc6545d09ee1c73/.github/workflows/release.yml

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout site repository
        uses: actions/checkout@v3
        with:
          path: site

      - name: Checkout creative writing repository
        uses: actions/checkout@v3
        with:
          repository: RiskoZoSlovenska/creative-writing
          path: creative-writing
          submodules: recursive
          token: ${{ secrets.GIT_CREDENTIALS }}


      - name: Install lua # Must install lua for luarocks to work
        uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: "5.1"
      
      - name: Install luarocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Install luvit
        # Borrowed (and modified) from
        # https://github.com/Lyrth/lit-test-package/blob/f5c8897100b923b892d1a3d8b4b34af26162f562/.github/actions/lit-download-action/action.yaml#L26-L28
        run: curl -L https://github.com/luvit/lit/raw/master/get-lit.sh | sed 's/curl /curl --retry 5 --retry-delay 10 /' | sh
      
      # I dunno how to get this working without manually installing libyaml
      - name: Install libyaml
        run: | # https://unix.stackexchange.com/a/85195
          curl -L --retry 5 --retry-delay 30 http://pyyaml.org/download/libyaml/yaml-0.2.5.tar.gz | tar xvz
          cd yaml-0.2.5
          ./configure
          make
          sudo make install

      - name: Install dependencies
        run: |
          luarocks install lcmark
          luarocks install lyaml
          luarocks install gumbo
        shell: bash


      - name: Compile stories
        run: ../luvit deploy-scripts/compile-stories.lua ../creative-writing
        shell: bash
        working-directory: site

      - name: Compile search data
        run: ../luvit deploy-scripts/compile-search-data.lua
        shell: bash
        working-directory: site


      - name: Push to deployment branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: site
          branch: gh-pages
          push_options: --force
          skip_checkout: true
          commit_message: Publish site
          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>