name: Perform Automatic Maintenance

on:
  workflow_dispatch:
  push:
    paths:
      - "**.html"
      - "**.js"
      - "**.lua"
      - ".github"
      - "!stories/**"

jobs:
  maintenance:
    runs-on: ubuntu-latest

    steps:
      # Setup
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup

      # Update stories
      - run: |
          CLONE_DIR=$(mktemp -d)

          git clone --recursive --single-branch --branch "master" https://${{ secrets.GIT_CREDENTIALS }}@github.com/RiskoZoSlovenska/creative-writing.git "$CLONE_DIR"

          ./luvit ./compile-stories.lua "$CLONE_DIR"

          git status
      
      # Update search data
      - run: |
          ./luvit ./compile-search-data.lua

          git status
      
      # Commit changes
      - run: git status
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatic Maintenance
          file_pattern: stories/** search_data.json


          
